(gcd.py:10):
-> 10 [38;5;94m"""[39m
Set basename (short filenames) in debugger output is on.
Set event tracing is on.
Set stopping before def or class statements is off.
No macros defined.
Macro "foo" defined.
  5    	[38;5;94mnot have a 'return' statement.[39m
  6    	
  7    	[38;5;94mcheck_args() raises an uncaught exception when given the wrong number[39m
  8    	[38;5;94mof parameters.[39m
  9    	
 10  ->	[38;5;94m"""[39m
 11    	[38;5;24;01mimport[39;00m [38;5;0msys[39m
 12    	
 13    	[38;5;24;01mdef[39;00m [38;5;0mcheck_args[39m[38;5;0;01m([39;00m[38;5;0;01m)[39;00m[38;5;0;01m:[39;00m
 14    	    [38;5;24;01mif[39;00m [38;5;24mlen[39m[38;5;0;01m([39;00m[38;5;0msys[39m[38;5;166;01m.[39;00m[38;5;0margv[39m[38;5;0;01m)[39;00m [38;5;166;01m!=[39;00m [38;5;20;01m3[39;00m[38;5;0;01m:[39;00m
foo

Macro "bar" defined.
  1    	[38;5;94m#!/usr/bin/python[39m
  2    	[38;5;94m"""Greatest Common Divisor[39m
  3    	
  4    	[38;5;94mSome characterstics of this program used for testing check_args() does[39m
  5    	[38;5;94mnot have a 'return' statement.[39m
  6    	
  7    	[38;5;94mcheck_args() raises an uncaught exception when given the wrong number[39m
  8    	[38;5;94mof parameters.[39m
  9    	
 10  ->	[38;5;94m"""[39m
 11    	[38;5;24;01mimport[39;00m [38;5;0msys[39m
    bar  foo

bar:
----
  lambda count: 'list %s' % count
foo:
----
  lambda: 'list'
trepan2: That's all, folks...
